version: '3'

services:
  front:
    container_name: pyccel-front
    build:
      context: ./frontend/.
      dockerfile: ./Dockerfile
      # network: host
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '3000:3000'
    networks:
      - PyccelNetwork

  backend:
    container_name: pyccel-backend
    build:
      context: ./backend/.
      dockerfile: ./Dockerfile
      # network: host
    ports:
      - '8000:8000'
    networks:
      - PyccelNetwork

networks:
  PyccelNetwork:
    driver: bridge
